apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^books_cbv/', include('books_cbv.urls', namespace='books_cbv')),
    url(r'^movies_cbv/', include('movies_cbv.urls', namespace='movies_cbv')),
    url(r'^music_cbv/', include('music_cbv.urls', namespace='music_cbv')),
    url(r'^$', 'apps.views.home'),
]

books_cbv/urls.py
from django.conf.urls import patterns, url

from books_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.BookList.as_view(), name='book_list'),
  url(r'^new$', views.BookCreate.as_view(), name='book_new'),
  url(r'^edit/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
)

movies_cbv/templates/movies_cbv/urls.py
from django.conf.urls import patterns, url

from movies_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.MovieList.as_view(), name='movie_list'),
  url(r'^new$', views.MovieCreate.as_view(), name='movie_new'),
  url(r'^edit/(?P<pk>\d+)$', views.MovieUpdate.as_view(), name='movie_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.MovieDelete.as_view(), name='movie_delete'),
)

movies_cbv/urls.py
from django.conf.urls import patterns, url

from movies_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.MovieList.as_view(), name='movie_list'),
  url(r'^new$', views.MovieCreate.as_view(), name='movie_new'),
  url(r'^edit/(?P<pk>\d+)$', views.MovieUpdate.as_view(), name='movie_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.MovieDelete.as_view(), name='movie_delete'),
)

music_cbv/urls.py
from django.conf.urls import patterns, url

from music_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.MusicList.as_view(), name='music_list'),
  url(r'^new$', views.MusicCreate.as_view(), name='music_new'),
  url(r'^edit/(?P<pk>\d+)$', views.MusicUpdate.as_view(), name='music_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.MusicDelete.as_view(), name='music_delete'),
)

books_cbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()
    amount = models.IntegerField()
    limpo = models.CharField(max_length=20)
    comentario = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

        def get_absolute_url(self):
            return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

movies_cbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Movie(models.Model):
    name = models.CharField(max_length=200)
    director =  models.CharField(max_length=200)
    amount = models.IntegerField()
    limpo = models.CharField(max_length=20)
    comentario = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

        def get_absolute_url(self):
            return reverse('movies_cbv:movie_edit', kwargs={'pk': self.pk})

music_cbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Music(models.Model):
    name = models.CharField(max_length=200)
    band =  models.CharField(max_length=200)
    amount = models.IntegerField()
    limpo = models.CharField(max_length=20)
    comentario = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

        def get_absolute_url(self):
            return reverse('music_cbv:music_edit', kwargs={'pk': self.pk})

apps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request):
    return render(request, 'index.html')



    # html = """
    # <h1>Django CRUD Example</h1>
    # <a href="/books_cbv/">Class Based Views</a><br>
    # <a href="/books_fbv/">Function Based Views</a><br>
    # <a href="/books_fbv_user/">Function Based Views with User Access</a><br>
    # """

books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from books_cbv.models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    fields = ['name', 'pages','amount','limpo','comentario']
    success_url = reverse_lazy('books_cbv:book_list')

class BookUpdate(UpdateView):
    model = Book
    fields =  ['name', 'pages','amount','limpo','comentario']
    success_url = reverse_lazy('books_cbv:book_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

movies_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from movies_cbv.models import Movie

class MovieList(ListView):
    model = Movie

class MovieCreate(CreateView):
    model = Movie
    fields = ['name', 'director','amount','limpo','comentario']
    success_url = reverse_lazy('movies_cbv:movie_list')

class MovieUpdate(UpdateView):
    model = Movie
    fields = ['name', 'director','amount','limpo','comentario']
    success_url = reverse_lazy('movies_cbv:movie_list')

class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('movies_cbv:movie_list')

music_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from music_cbv.models import Music

class MusicList(ListView):
    model = Music

class MusicCreate(CreateView):
    model = Music
    fields = ['name', 'band','amount','limpo','comentario']
    success_url = reverse_lazy('music_cbv:music_list')

class MusicUpdate(UpdateView):
    model = Music
    fields = ['name', 'band','amount','limpo','comentario']
    success_url = reverse_lazy('music_cbv:music_list')

class MusicDelete(DeleteView):
    model = Music
    success_url = reverse_lazy('music_cbv:music_list')

books_cbv/templates/books_cbv/book_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

books_cbv/templates/books_cbv/book_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

books_cbv/templates/books_cbv/book_list.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Books</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">
</head>
<body>
  <section class="hero is-fullheight is-primary">
    <div class="hero-head">
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h3 class="title is-2">Books!</h3>
        <div class="content">
          <ul>
            {% for book in object_list %}
            <li>Nome: {{book.name}} </br>Pages: {{book.pages}}</br> {% if book.amount > 10 %}
                                                                                                                Quantidade <bold>(alta)</bold> {{book.amount}}</br>
                                                                                                                ,{% else %}
                                                                                                                 Quantidade <bold>(baixa)</bold>: {{book.amount}}</br>
                                                                                                                 {% endif %}
            Limpo: {{book.limpo}}</br> Comentário: {{book.comentario}}</li><br>
            <a class="button" href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
            <a class="button" href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
            <br><br>
            {% empty %}
            <h2 class="subtitle">Nenhum livro em estoque.</h2>
            <a  class="button" href="{% url 'books_cbv:book_new' %}">Criar</a>
            {% endfor %}
          </ul>
          <a class="button" href="{% url 'books_cbv:book_new' %}">Criar</a>
        </div>

      </div>
    </div>

  </section>

</body>
</html>

books_cbv/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Desafio</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">
</head>
<body>
  <section class="hero is-fullheight is-dark is-bold">
    <div class="hero-head">
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h3 class="title is-3">Desafio Yenzah!</h3><br><br><br>
        <a class="title is-1" href="/books_cbv/">Books Store!</a><br><br>
        <a class="title is-1" href="/movies_cbv/">Movies  Store!</a><br><br>
        <a class="title is-1" href="/music_cbv/">Music Store!</a><br><br>
      </div>
    </div>

  </section>

</body>
</html>







<!-- <h1>Books CBV</h1>
<ul>
{% for book in object_list %}
<li>{{ book.name }}  ({{ book.pages }} Pages) ({{book.amount}} Amount)
<a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
<a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
</li>
{% endfor %}
</ul>

<a href="{% url 'books_cbv:book_new' %}">New</a> -->

movies_cbv/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Desafio</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">
</head>
<body>
  <section class="hero is-fullheight is-dark is-bold">
    <div class="hero-head">
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h3 class="title is-3">Desafio Yenzah!</h3><br><br><br>
        <a class="title is-1" href="/books_cbv/">Books Store!</a><br><br>
        <a class="title is-1" href="/books_fbv/">Movies  Store!</a><br><br>
        <a class="title is-1" href="/books_fbv_user/">Music Store!</a><br><br>
      </div>
    </div>

  </section>

</body>
</html>







<!-- <h1>Books CBV</h1>
<ul>
{% for book in object_list %}
<li>{{ book.name }}  ({{ book.pages }} Pages) ({{book.amount}} Amount)
<a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
<a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
</li>
{% endfor %}
</ul>

<a href="{% url 'books_cbv:book_new' %}">New</a> -->

movies_cbv/templates/movies_cbv/movie_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

movies_cbv/templates/movies_cbv/movie_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

movies_cbv/templates/movies_cbv/movie_list.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Movies</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">
</head>
<body>
  <section class="hero is-fullheight is-danger is-bold">
    <div class="hero-head">
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h3 class="title is-2">Movies!</h3>
        <div class="content">
          <ul>
            {% for movie in object_list %}
            <li>Nome: {{movie.name}} </br>Diretor: {{movie.director}}</br> {% if movie.amount > 10 %}
                                                                                                                Quantidade <bold>(alta)</bold> {{movie.amount}}</br>
                                                                                                                ,{% else %}
                                                                                                                 Quantidade <bold>(baixa)</bold>: {{movie.amount}}</br>
                                                                                                                 {% endif %}
            Limpo: {{movie.limpo}}</br> Comentário: {{movie.comentario}}</li><br>
            <a class="button" href="{% url 'movies_cbv:movie_edit' movie.id %}">edit</a>
            <a class="button" href="{% url 'movies_cbv:movie_delete' movie.id %}">delete</a>
            <br><br>
            {% empty %}
            <h2 class="subtitle">Nenhum filme em estoque.</h2>
            {% endfor %}
          </ul>
          <a class="button" href="{% url 'movies_cbv:movie_new' %}">Criar</a>
        </div>

      </div>
    </div>

  </section>

</body>
</html>







<!-- <h1>movies CBV</h1>
<ul>
{% for movie in object_list %}
<li>{{ movie.name }}  ({{ movie.pages }} Pages) ({{movie.amount}} Amount)
<a href="{% url 'movies_cbv:movie_edit' movie.id %}">edit</a>
<a href="{% url 'movies_cbv:movie_delete' movie.id %}">delete</a>
</li>
{% endfor %}
</ul>

<a href="{% url 'movies_cbv:movie_new' %}">New</a> -->

music_cbv/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Desafio</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">
</head>
<body>
  <section class="hero is-fullheight is-dark is-bold">
    <div class="hero-head">
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h3 class="title is-3">Desafio Yenzah!</h3><br><br><br>
        <a class="title is-1" href="/books_cbv/">Books Store!</a><br><br>
        <a class="title is-1" href="/books_fbv/">Movies  Store!</a><br><br>
        <a class="title is-1" href="/books_fbv_user/">Music Store!</a><br><br>
      </div>
    </div>

  </section>

</body>
</html>







<!-- <h1>Books CBV</h1>
<ul>
{% for book in object_list %}
<li>{{ book.name }}  ({{ book.pages }} Pages) ({{book.amount}} Amount)
<a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
<a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
</li>
{% endfor %}
</ul>

<a href="{% url 'books_cbv:book_new' %}">New</a> -->

music_cbv/templates/music_cbv/music_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

music_cbv/templates/music_cbv/music_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

music_cbv/templates/music_cbv/music_list.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Music</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">
</head>
<body>
  <section class="hero is-fullheight is-warning is-bold">
    <div class="hero-head">
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h3 class="title is-2">Music!</h3>
        <div class="content">
          <ul>
            {% for music in object_list %}
            <li>Nome: {{music.name}} </br>Band: {{music.band}}</br> {% if music.amount > 10 %}
                                                                                                                Quantidade <bold>(alta)</bold> {{music.amount}}</br>
                                                                                                                ,{% else %}
                                                                                                                 Quantidade <bold>(baixa)</bold>: {{music.amount}}</br>
                                                                                                                 {% endif %}
            Limpo: {{music.limpo}}</br> Comentário: {{music.comentario}}</li><br>
            <a class="button" href="{% url 'music_cbv:music_edit' music.id %}">edit</a>
            <a class="button" href="{% url 'music_cbv:music_delete' music.id %}">delete</a>
            <br><br>
            {% empty %}
            <h2 class="subtitle">Nenhum música em estoque.</h2>
            {% endfor %}
          </ul>
          <a class="button" href="{% url 'music_cbv:music_new' %}">Criar</a>
        </div>

      </div>
    </div>

  </section>

</body>
</html>